 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.airliner;

import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.AirlinerDirectory;;

/**
 *
 * @author kavit
 */

   public class AirlinerDirectoryJPanel extends javax.swing.JPanel {
       
       
    private AirlinerDirectory airliner1;
    private JPanel rightJPanel;
    public AirlinerDirectoryJPanel (JPanel rightJPanel, AirlinerDirectory airliner1){
        initComponents();
        this.airliner1 = airliner1;
        this.rightJPanel = rightJPanel;
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workArea = new javax.swing.JLabel();
        btnDirectory = new javax.swing.JButton();

        setBackground(new java.awt.Color(129, 235, 239));

        workArea.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        workArea.setText("Work Area of Airliner");

        btnDirectory.setText("Airliner Directory");
        btnDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(workArea))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(btnDirectory)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(workArea)
                .addGap(94, 94, 94)
                .addComponent(btnDirectory)
                .addContainerGap(437, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectoryActionPerformed
        // TODO add your handling code here:
        AirlinerManager am = new AirlinerManager(rightJPanel,airliner1);
        rightJPanel.add("AirlinerManager", am);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_btnDirectoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDirectory;
    private javax.swing.JLabel workArea;
    // End of variables declaration//GEN-END:variables
}
